{% snapshot snp_action_secondary_all %}
{#
    Snapshot for historical tracking of action_secondary records.
    
    This replaces the Oracle pattern of inserting into action_secondary_all
    from nwk_action_secondary_tbl where event_id in (select event_id from 
    nwk_action_primary_tbl where load_date = trunc(sysdate)).
    
    dbt snapshots use SCD Type 2 to track historical changes automatically.
#}

{{
    config(
        target_schema='snapshots',
        unique_key='event_id',
        strategy='timestamp',
        updated_at='_loaded_at',
        invalidate_hard_deletes=True
    )
}}

select
    event_id,
    adtnl_opt_life_ins_cd,
    allot_cd,
    allot_ded_amt,
    allot_eff_dte,
    allot_emp_acct_num,
    allot_emp_acct_type_cd,
    allot_fincl_instn_city_st_name,
    allot_fincl_instn_name,
    allot_fincl_instn_num,
    allot_fincl_instn_postal_cd,
    allot_fincl_instn_street_name,
    bond_coben_cd,
    bond_coben_name,
    bond_coben_ssn,
    bond_denom_cd,
    bond_inscription_num,
    bond_note_tot_ded_amt,
    bond_owner_city_name,
    bond_owner_name,
    bond_owner_postal_cd,
    bond_owner_ssn,
    bond_owner_st_name,
    bond_owner_street_name,
    bond_refund_ind,
    buyout_amt,
    buyout_eff_dte,
    claim_type_cd,
    cola_pct,
    court_order_applctn_cd,
    csa_cd,
    csa_ded_amt,
    csa_ded_pct,
    csa_recipient_name,
    csrs_admin_fee_cd,
    envirn_dif_pct,
    family_life_ins_cd,
    forgn_lang_award_amt,
    garnishment_cd,
    garnishment_ded_amt,
    garnishment_ded_pct,
    garnishment_recipient_name,
    hazard_pay_pct,
    health_benefits_cd,
    health_benefits_prior_cd,
    incentive_award_amt,
    incentive_award_dte,
    incentive_award_noa_cd,
    legal_auth1_cd,
    legal_auth1_desc,
    legal_auth1_desc2,
    legal_auth2_cd,
    legal_auth2_desc,
    legal_auth2_desc2,
    life_ins_cd,
    life_ins_prior_cd,
    mil_lv_cur_fy_hrs,
    mil_lv_prior_fy_hrs,
    opt_life_ins_cd,
    opt_life_ins_prior_cd,
    perf_award_amt,
    perf_award_dte,
    perf_award_noa_cd,
    recruitment_bonus_amt,
    recruitment_bonus_dte,
    relocation_bonus_amt,
    relocation_bonus_dte,
    retention_bonus_amt,
    retention_bonus_dte,
    retnd1_grade_cd,
    retnd1_pay_plan_cd,
    retnd1_step_cd,
    retnd1_basic_pay_amt,
    retnd1_locality_adj_amt,
    retnd1_adj_basic_pay_amt,
    retnd1_total_pay_amt,
    retnd1_pay_basis_cd,
    retnd1_work_sched_cd,
    retnd1_part_time_hrs,
    retnd1_occ_series_cd,
    retnd1_position_title_cd,
    retnd1_position_title_off,
    retnd1_expiration_dte,
    retnd1_wgi_due_dte,
    retnd1_wgi_status_cd,
    retnd1_legal_auth_cd,
    sick_lv_cur_bal_hrs,
    sick_lv_prior_year_bal_hrs,
    sick_lv_ytd_accrd_hrs,
    sick_lv_ytd_used_hrs,
    time_off_award_amt,
    time_off_granted_hrs,
    tsp_cd,
    tsp_contrib_pct,
    tsp_ded_amt,
    tsp_prior_cd,
    unif_svc_mon,
    mil_status_cd,
    veterans_pref_cd,
    veterans_pref_rif_cd,
    award_type_cd,
    award_amt,
    award_pct,
    award_hrs,
    award_dte,
    award_noa_cd,
    paygroup,
    leo_scd_dt,
    retention_bonus_end_date,
    _loaded_at
from {{ ref('fct_action_secondary') }}

{% endsnapshot %}
