{{
    config(
        materialized='view',
        tags=['staging', 'ehrp2biis']
    )
}}

with source as (
    select * from {{ source('ehrp_raw', 'ps_gvt_job') }}
),

staged as (
    select
        emplid,
        empl_rcd::number(38,0) as empl_rcd,
        effdt::date as effdt,
        effseq::number(38,0) as effseq,
        deptid,
        jobcode,
        position_nbr,
        position_override,
        posn_change_record,
        empl_status,
        action,
        action_dt::date as action_dt,
        action_reason,
        location,
        tax_location_cd,
        job_entry_dt::date as job_entry_dt,
        dept_entry_dt::date as dept_entry_dt,
        position_entry_dt::date as position_entry_dt,
        shift,
        reg_temp,
        full_part_time,
        company,
        paygroup,
        bas_group_id,
        elig_config1,
        elig_config2,
        elig_config3,
        elig_config4,
        elig_config5,
        elig_config6,
        elig_config7,
        elig_config8,
        elig_config9,
        ben_status,
        bas_action,
        cobra_action,
        empl_type,
        holiday_schedule,
        std_hours::number(6,2) as std_hours,
        std_hrs_frequency,
        officer_cd,
        empl_class,
        sal_admin_plan,
        grade,
        grade_entry_dt::date as grade_entry_dt,
        step::number(38,0) as step,
        step_entry_dt::date as step_entry_dt,
        gl_pay_type,
        acct_cd,
        earns_dist_type,
        comp_frequency,
        comprate::number(18,6) as comprate,
        change_amt::number(18,6) as change_amt,
        change_pct::number(6,3) as change_pct,
        annual_rt::number(18,3) as annual_rt,
        monthly_rt::number(18,3) as monthly_rt,
        daily_rt::number(18,3) as daily_rt,
        hourly_rt::number(18,6) as hourly_rt,
        annl_benef_base_rt::number(18,3) as annl_benef_base_rt,
        shift_rt::number(18,6) as shift_rt,
        shift_factor::number(4,3) as shift_factor,
        currency_cd,
        business_unit,
        setid_dept,
        setid_jobcode,
        setid_location,
        setid_salary,
        reg_region,
        directly_tipped,
        flsa_status,
        eeo_class,
        function_cd,
        gvt_effdt::date as gvt_effdt,
        gvt_effdt_proposed::date as gvt_effdt_proposed,
        gvt_trans_nbr::number(38,0) as gvt_trans_nbr,
        gvt_trans_nbr_seq::number(38,0) as gvt_trans_nbr_seq,
        gvt_wip_status,
        gvt_status_type,
        gvt_noa_code,
        gvt_leg_auth_1,
        gvt_par_auth_d1,
        gvt_par_auth_d1_2,
        gvt_leg_auth_2,
        gvt_par_auth_d2,
        gvt_par_auth_d2_2,
        gvt_noa_code2,
        gvt_noac_suffix,
        gvt_noac_suffix2,
        gvt_pay_plan,
        gvt_pay_plan_prior,
        gvt_grade,
        gvt_grade_prior,
        gvt_step,
        gvt_step_prior,
        gvt_comprate::number(18,6) as gvt_comprate,
        gvt_comprate_prior::number(18,6) as gvt_comprate_prior,
        gvt_locality_adj::number(18,6) as gvt_locality_adj,
        gvt_locality_adj_prior::number(18,6) as gvt_locality_adj_prior,
        gvt_adj_base_pay::number(18,6) as gvt_adj_base_pay,
        gvt_adj_base_pay_prior::number(18,6) as gvt_adj_base_pay_prior,
        gvt_total_salary::number(18,6) as gvt_total_salary,
        gvt_total_salary_prior::number(18,6) as gvt_total_salary_prior,
        gvt_ann_sal_prorated::number(18,6) as gvt_ann_sal_prorated,
        gvt_ann_sal_prorated_pr::number(18,6) as gvt_ann_sal_prorated_pr,
        gvt_pay_basis,
        gvt_pay_basis_prior,
        gvt_work_sched,
        gvt_work_sched_prior,
        gvt_part_time_hrs::number(6,2) as gvt_part_time_hrs,
        gvt_part_time_hrs_prior::number(6,2) as gvt_part_time_hrs_prior,
        gvt_occ_series,
        gvt_occ_series_prior,
        gvt_posn_title_cd,
        gvt_posn_title_cd_prior,
        gvt_posn_title_off,
        gvt_posn_title_off_pr,
        gvt_duty_station,
        gvt_duty_station_prior,
        gvt_poi,
        gvt_poi_prior,
        gvt_agency_code,
        gvt_agency_code_prior,
        gvt_sub_agency,
        gvt_sub_agency_prior,
        gvt_personnel_office,
        gvt_personnel_off_prior,
        gvt_appt_type,
        gvt_appt_type_prior,
        gvt_appt_limit_dt::date as gvt_appt_limit_dt,
        gvt_appt_limit_dt_prior::date as gvt_appt_limit_dt_prior,
        gvt_tenure,
        gvt_tenure_prior,
        gvt_fegli,
        gvt_fegli_prior,
        gvt_fehb,
        gvt_fehb_prior,
        gvt_retirement_plan,
        gvt_retire_plan_prior,
        gvt_fers_coverage,
        gvt_fers_coverage_prior,
        gvt_annuity_offset,
        gvt_annuity_offset_prior,
        gvt_flsa_status,
        gvt_flsa_status_prior,
        gvt_bargain_unit,
        gvt_bargain_unit_prior,
        gvt_supv_status,
        gvt_supv_status_prior,
        gvt_cyber_sec_cd,
        gvt_cyber_sec_cd_prior,
        gvt_scd_wgi::date as gvt_scd_wgi,
        gvt_scd_leave::date as gvt_scd_leave,
        gvt_scd_retire::date as gvt_scd_retire,
        gvt_scd_rif::date as gvt_scd_rif,
        gvt_scd_ses::date as gvt_scd_ses,
        gvt_scd_tsp::date as gvt_scd_tsp,
        gvt_scd_spcl_retire::date as gvt_scd_spcl_retire,
        gvt_prob_dt_civil::date as gvt_prob_dt_civil,
        gvt_prob_dt_supv::date as gvt_prob_dt_supv,
        gvt_prob_dt_ses::date as gvt_prob_dt_ses,
        gvt_wgi_due_dt::date as gvt_wgi_due_dt,
        gvt_wgi_status,
        gvt_rtnd_grade,
        gvt_rtnd_pay_plan,
        gvt_rtnd_step,
        gvt_rtnd_comprate::number(18,6) as gvt_rtnd_comprate,
        gvt_rtnd_loc_adj::number(18,6) as gvt_rtnd_loc_adj,
        gvt_rtnd_adj_base::number(18,6) as gvt_rtnd_adj_base,
        gvt_rtnd_tot_salary::number(18,6) as gvt_rtnd_tot_salary,
        gvt_rtnd_pay_basis,
        gvt_rtnd_sched,
        gvt_rtnd_pt_hrs::number(6,2) as gvt_rtnd_pt_hrs,
        gvt_rtnd_occ_series,
        gvt_rtnd_posn_title,
        gvt_rtnd_posn_off,
        gvt_rtnd_exp_dt::date as gvt_rtnd_exp_dt,
        gvt_rtnd_wgi_dt::date as gvt_rtnd_wgi_dt,
        gvt_rtnd_wgi_status,
        gvt_rtnd_legal_auth,
        gvt_veterans_pref,
        gvt_veterans_pref_rif,
        gvt_mil_status,
        gvt_unif_svc_mon::number(4,0) as gvt_unif_svc_mon,
        gvt_award_type,
        gvt_award_amount::number(18,6) as gvt_award_amount,
        gvt_award_pct::number(6,3) as gvt_award_pct,
        gvt_award_hours::number(6,2) as gvt_award_hours,
        gvt_award_date::date as gvt_award_date,
        gvt_award_noa,
        gvt_remarks,
        current_timestamp() as _loaded_at
    from source
)

select * from staged
