"""AUTO-DERIVED from Informatica XML metadata. Do not edit by hand.
Source: XML/Pseudossn :: PSEUDOSSN_FILE_TK_NUM (fixed-width flat file)
"""

from pyspark_etl.config.schemas import FixedField

PSEUDOSSN_FILE_TK_NUM = [
    FixedField('SSN', offset=0, length=9, datatype='string', precision=9, scale=0),
    FixedField('CAN_CD', offset=9, length=8, datatype='string', precision=8, scale=0),
    FixedField('PSEUDO_SSN', offset=17, length=9, datatype='string', precision=9, scale=0),
    FixedField('EIN', offset=26, length=8, datatype='string', precision=8, scale=0),
    FixedField('EMP_REC_NO', offset=34, length=2, datatype='string', precision=2, scale=0),
    FixedField('LEGACY_APPT_NO', offset=36, length=2, datatype='string', precision=2, scale=0),
    FixedField('FIRST_NAME', offset=38, length=11, datatype='string', precision=11, scale=0),
    FixedField('MIDDLE_INIT', offset=49, length=1, datatype='string', precision=1, scale=0),
    FixedField('LAST_NAME', offset=50, length=16, datatype='string', precision=16, scale=0),
    FixedField('SEX', offset=66, length=1, datatype='string', precision=1, scale=0),
    FixedField('VET_PREF', offset=67, length=1, datatype='string', precision=1, scale=0),
    FixedField('TENURE_CD', offset=68, length=1, datatype='string', precision=1, scale=0),
    FixedField('POSITION_CD', offset=69, length=1, datatype='string', precision=1, scale=0),
    FixedField('CITIZENSHIP_STATUS', offset=70, length=1, datatype='string', precision=1, scale=0),
    FixedField('APPT_TYPE_CD', offset=71, length=2, datatype='string', precision=2, scale=0),
    FixedField('HIRE_DATE', offset=73, length=8, datatype='string', precision=8, scale=0),
    FixedField('HANDICAP_CODE', offset=81, length=2, datatype='string', precision=2, scale=0),
    FixedField('UNIF_ALLOW_CODE', offset=83, length=3, datatype='string', precision=3, scale=0),
    FixedField('UNIF_ALLOW_DATE', offset=86, length=8, datatype='string', precision=8, scale=0),
    FixedField('UNIF_ALLOW_AMT', offset=94, length=6, datatype='string', precision=6, scale=0),
    FixedField('RSSSDP', offset=100, length=4, datatype='string', precision=4, scale=0),
    FixedField('CEILING_CODE', offset=104, length=1, datatype='string', precision=1, scale=0),
    FixedField('FUNCTION_CODE', offset=105, length=1, datatype='string', precision=1, scale=0),
    FixedField('EMPLOYEE_STATUS', offset=106, length=1, datatype='string', precision=1, scale=0),
    FixedField('MANAGER_STATUS', offset=107, length=1, datatype='string', precision=1, scale=0),
    FixedField('POSITION_SENS_CODE', offset=108, length=1, datatype='string', precision=1, scale=0),
    FixedField('CAREER_START_DATE', offset=109, length=8, datatype='string', precision=8, scale=0),
    FixedField('CAREER_CONV_DATE', offset=117, length=8, datatype='string', precision=8, scale=0),
    FixedField('PROBATION_DATE', offset=125, length=8, datatype='string', precision=8, scale=0),
    FixedField('ABNORMAL_RATE_CODE', offset=133, length=1, datatype='string', precision=1, scale=0),
    FixedField('APPT_LIMIT_HRS', offset=134, length=7, datatype='string', precision=7, scale=0),
    FixedField('APPT_LIMIT_PAY', offset=141, length=8, datatype='string', precision=8, scale=0),
    FixedField('LAST_PAY_CHANGE', offset=149, length=8, datatype='string', precision=8, scale=0),
    FixedField('CHARITY_AREA_CODE', offset=157, length=3, datatype='string', precision=3, scale=0),
    FixedField('CHARITY_EFF_DATE', offset=160, length=8, datatype='string', precision=8, scale=0),
    FixedField('CHARITY_DED_AMT', offset=168, length=6, datatype='string', precision=6, scale=0),
    FixedField('LAST_NOA', offset=174, length=4, datatype='string', precision=4, scale=0),
    FixedField('FILLER_1', offset=178, length=4, datatype='string', precision=4, scale=0),
    FixedField('QUARTERS_DEDUCTION', offset=182, length=8, datatype='string', precision=8, scale=0),
    FixedField('SUBSIST_DEDUCTION', offset=190, length=8, datatype='string', precision=8, scale=0),
    FixedField('PAY_BASIS', offset=198, length=2, datatype='string', precision=2, scale=0),
    FixedField('WORK_SCHEDULE', offset=200, length=1, datatype='string', precision=1, scale=0),
    FixedField('OCCUPATION_CODE', offset=201, length=4, datatype='string', precision=4, scale=0),
    FixedField('FILLER_2', offset=205, length=3, datatype='string', precision=3, scale=0),
    FixedField('GEO_LOCATION', offset=208, length=9, datatype='string', precision=9, scale=0),
    FixedField('JOB_INDICATOR', offset=217, length=1, datatype='string', precision=1, scale=0),
    FixedField('REG_TEMP', offset=218, length=1, datatype='string', precision=1, scale=0),
    FixedField('SEPARATION_DATE', offset=219, length=8, datatype='string', precision=8, scale=0),
    FixedField('FILLER_3', offset=227, length=1, datatype='string', precision=1, scale=0),
    FixedField('PCA_CONTR_EFF_START_DATE', offset=228, length=8, datatype='string', precision=8, scale=0),
    FixedField('PCA_CONTR_EFF_END_DATE', offset=236, length=8, datatype='string', precision=8, scale=0),
    FixedField('MAX_ANNUAL_PAY', offset=244, length=8, datatype='string', precision=8, scale=0),
    FixedField('PCA_BIWEEKLY_AMOUNT', offset=252, length=8, datatype='string', precision=8, scale=0),
    FixedField('FILLER_4', offset=260, length=33, datatype='string', precision=33, scale=0),
    FixedField('PAY_PLAN_CD', offset=293, length=2, datatype='string', precision=2, scale=0),
    FixedField('APP_LIMIT_DATE', offset=295, length=8, datatype='string', precision=8, scale=0),
    FixedField('SPO_CD', offset=303, length=4, datatype='string', precision=4, scale=0),
    FixedField('TERM_ID', offset=307, length=2, datatype='string', precision=2, scale=0),
    FixedField('EFFECTIVE_DATE', offset=309, length=8, datatype='string', precision=8, scale=0),
    FixedField('EFFECTIVE_SEQ', offset=317, length=3, datatype='string', precision=3, scale=0),
    FixedField('FILLER_5', offset=320, length=9, datatype='string', precision=9, scale=0),
    FixedField('PAY_TABL_NO', offset=329, length=4, datatype='string', precision=4, scale=0),
    FixedField('BUSINESS_UNIT', offset=333, length=5, datatype='string', precision=5, scale=0),
    FixedField('DEPTID', offset=338, length=10, datatype='string', precision=10, scale=0),
    FixedField('PCA_CONTR_YEAR', offset=348, length=2, datatype='string', precision=2, scale=0),
    FixedField('FILLER_6', offset=350, length=150, datatype='string', precision=150, scale=0),
    FixedField('TK_NUM', offset=500, length=5, datatype='string', precision=5, scale=0),
]
