-- Auto-generated from utils.schemas for SQL Server
IF OBJECT_ID('dbo.PAY_PERIOD', 'U') IS NOT NULL DROP TABLE dbo.PAY_PERIOD;
GO
CREATE TABLE PAY_PERIOD (
    PP_NUM INT,
    PP_END_YEAR INT,
    PP_START_DTE DATETIME2,
    PP_END_DTE DATETIME2,
    LV_NUM INT,
    LV_YEAR INT,
    PAY_DTE DATETIME2,
    CURR_PP_FLAG VARCHAR(1),
    HOLIDAY_1 DATETIME2,
    HOLIDAY_2 DATETIME2
);
GO
