-- Auto-generated from utils.schemas for SQL Server
IF OBJECT_ID('dbo.COMP_TIME_DAILY_TBL', 'U') IS NOT NULL DROP TABLE dbo.COMP_TIME_DAILY_TBL;
GO
CREATE TABLE COMP_TIME_DAILY_TBL (
    PP_END_YEAR INT,
    PP_NUM INT,
    PP_YEAR_NUM INT,
    SSN VARCHAR(9),
    NAME VARCHAR(30),
    CURRENT_ACCT VARCHAR(6),
    CURRENT_ORG VARCHAR(7),
    FLSA_STATUS VARCHAR(1),
    COMP_TIME_CUR_BAL DECIMAL(8,2),
    COMP_TIME_YEAR_EARNED INT,
    PP_END_DATE DATETIME2,
    DAILY_DATE_EARNED DATETIME2,
    COMP_TIME_RATE DECIMAL(6,2),
    COMP_TIME_HOURS DECIMAL(8,2),
    COMP_TIME_UNDEF INT
);
GO
