-- Auto-generated from utils.schemas for SQL Server
IF OBJECT_ID('dbo.COUNTER_TBL', 'U') IS NOT NULL DROP TABLE dbo.COUNTER_TBL;
GO
CREATE TABLE COUNTER_TBL (
    PROCESS_NAME VARCHAR(30),
    PP_END_YEAR INT,
    PP_NUM INT,
    COUNTER_VALUE BIGINT,
    RUN_DATE DATETIME2
);
GO
