-- Auto-generated from utils.schemas for SQL Server
IF OBJECT_ID('dbo.PSEUDOSSN_FROM_SDA_TBL', 'U') IS NOT NULL DROP TABLE dbo.PSEUDOSSN_FROM_SDA_TBL;
GO
CREATE TABLE PSEUDOSSN_FROM_SDA_TBL (
    PSEUDO_SSN VARCHAR(9),
    REAL_SSN VARCHAR(9),
    LAST_NAME VARCHAR(30),
    FIRST_NAME VARCHAR(20),
    EFFECTIVE_DATE DATETIME2,
    AMOUNT DECIMAL(10,2),
    RECORD_TYPE VARCHAR(1)
);
GO
