-- Auto-generated from utils.schemas for SQL Server
IF OBJECT_ID('dbo.HI_ARCH_PSEUDOSSN_TBL', 'U') IS NOT NULL DROP TABLE dbo.HI_ARCH_PSEUDOSSN_TBL;
GO
CREATE TABLE HI_ARCH_PSEUDOSSN_TBL (
    PSEUDO_SSN VARCHAR(9),
    REAL_SSN VARCHAR(9),
    LAST_NAME VARCHAR(30),
    FIRST_NAME VARCHAR(20),
    EFFECTIVE_DATE DATETIME2,
    AMOUNT DECIMAL(10,2),
    ARCHIVE_DATE DATETIME2
);
GO
