-- Auto-generated from utils.schemas for SQL Server
IF OBJECT_ID('dbo.HI_PM_FDA_TATRAN_TBL', 'U') IS NOT NULL DROP TABLE dbo.HI_PM_FDA_TATRAN_TBL;
GO
CREATE TABLE HI_PM_FDA_TATRAN_TBL (
    FDA_BATCH_ID VARCHAR(10),
    FDA_TK_NO VARCHAR(10),
    FDA_EMP_ID VARCHAR(9),
    PP_END_YEAR INT,
    PP_NUM INT,
    LEAVE_HOURS DECIMAL(8,2),
    LEAVE_TYPE VARCHAR(4)
);
GO
