-- Auto-generated from utils.schemas for SQL Server
IF OBJECT_ID('dbo.ERROR_TBL', 'U') IS NOT NULL DROP TABLE dbo.ERROR_TBL;
GO
CREATE TABLE ERROR_TBL (
    FDA_BATCH_ID VARCHAR(10),
    FDA_TK_NO VARCHAR(10),
    FDA_EMP_ID VARCHAR(9),
    ERROR_TYPE VARCHAR(30),
    ERROR_MSG VARCHAR(200),
    RUN_DATE DATETIME2
);
GO
