-- Auto-generated from utils.schemas for SQL Server
IF OBJECT_ID('dbo.CPM_MER_DETAIL_STG_TBL', 'U') IS NOT NULL DROP TABLE dbo.CPM_MER_DETAIL_STG_TBL;
GO
CREATE TABLE CPM_MER_DETAIL_STG_TBL (
    FDA_EMP_ID VARCHAR(9),
    PP_END_YEAR INT,
    PP_NUM INT,
    DETAIL_AMT DECIMAL(10,2)
);
GO
