-- Auto-generated from utils.schemas for SQL Server
IF OBJECT_ID('dbo.NWK_NEW_EHRP_ACTIONS_TBL', 'U') IS NOT NULL DROP TABLE dbo.NWK_NEW_EHRP_ACTIONS_TBL;
GO
CREATE TABLE NWK_NEW_EHRP_ACTIONS_TBL (
    EMPLID VARCHAR(11),
    EMPL_RCD BIGINT,
    EFFDT DATETIME2,
    EFFSEQ BIGINT
);
GO
