-- Auto-generated from utils.schemas for SQL Server
IF OBJECT_ID('dbo.EHRP_RECS_TRACKING_TBL', 'U') IS NOT NULL DROP TABLE dbo.EHRP_RECS_TRACKING_TBL;
GO
CREATE TABLE EHRP_RECS_TRACKING_TBL (
    EMPLID VARCHAR(8),
    EMPL_RCD INT,
    EFFDT DATETIME2,
    EFFSEQ INT,
    EVENT_SUBMITTED_DT DATETIME2,
    GVT_WIP_STATUS VARCHAR(3),
    NOA_CD VARCHAR(3),
    NOA_SUFFIX_CD VARCHAR(1),
    BIIS_EVENT_ID BIGINT,
    LOAD_DATE DATETIME2,
    BIIS_WIP_STATUS_CHANGED_DT DATETIME2
);
GO
