-- Auto-generated from utils.schemas for SQL Server
IF OBJECT_ID('dbo.NWK_ACTION_REMARKS_TBL', 'U') IS NOT NULL DROP TABLE dbo.NWK_ACTION_REMARKS_TBL;
GO
CREATE TABLE NWK_ACTION_REMARKS_TBL (
    EVENT_ID BIGINT,
    REMARK_SEQ INT,
    REMARK_CD VARCHAR(10),
    REMARK_TEXT VARCHAR(240),
    LOAD_DATE DATETIME2
);
GO
