-- Auto-generated from utils.schemas for SQL Server
IF OBJECT_ID('dbo.ACTION_REMARKS_ALL', 'U') IS NOT NULL DROP TABLE dbo.ACTION_REMARKS_ALL;
GO
CREATE TABLE ACTION_REMARKS_ALL (
    EVENT_ID BIGINT,
    REMARK_SEQ INT,
    REMARK_CD VARCHAR(10),
    REMARK_TEXT VARCHAR(240),
    LOAD_DATE DATETIME2
);
GO
