-- Auto-generated from utils.schemas for SQL Server
IF OBJECT_ID('dbo.CPM_NIH_STG_TBL', 'U') IS NOT NULL DROP TABLE dbo.CPM_NIH_STG_TBL;
GO
CREATE TABLE CPM_NIH_STG_TBL (
    PP_END_YEAR INT,
    PP_NUM INT,
    DFAS_PSEUDO_SSN VARCHAR(9),
    BUSINESS_UNIT VARCHAR(5),
    ORG_CDE VARCHAR(10),
    AGENCY VARCHAR(5),
    RECORD_COUNT INT
);
GO
