{{
    config(
        materialized='table',
        schema='marts'
    )
}}

with enriched_data as (
    select * from {{ ref('int_employee_enrichment') }}
),

transformed as (
    select
        event_id,
        {{ build_agency_assignment_code('company', 'gvt_sub_agency') }} as agcy_assign_cd,
        deptid as agcy_subelement_cd,
        {{ build_prior_agency_subelement('gvt_xfer_from_agcy') }} as agcy_subelement_prior_cd,
        null as ann_lv_45day_ceil_cd,
        null as ann_lv_catgry_cd,
        {{ zero_to_null('he_al_red_cred') }} as ann_lv_crdt_reductn_hrs,
        {{ zero_to_null('he_al_balance') }} as ann_lv_cur_bal_hrs,
        {{ zero_to_null('he_lump_hrs') }} as ann_lv_lump_sum_paid_hrs,
        {{ zero_to_null('he_al_carryover') }} as ann_lv_prior_year_bal_hrs,
        {{ zero_to_null('he_res_lastyr') }} as ann_lv_restored_bal_lv_hrs,
        {{ zero_to_null('he_res_balance') }} as ann_lv_restored_bal1_hrs,
        {{ zero_to_null('he_res_twoyrs') }} as ann_lv_restored_bal2_hrs,
        {{ zero_to_null('he_res_threeyrs') }} as ann_lv_restored_bal3_hrs,
        null as ann_lv_tranfr_in_bal_hrs,
        {{ zero_to_null('he_al_accrual') }} as ann_lv_ytd_accrd_hrs,
        {{ zero_to_null('he_al_total') }} as ann_lv_ytd_used_hrs,
        annual_rt as ann_salary_rate_amt,
        gvt_ann_ind as annuitant_ind_cd,
        null as appointing_office_change_cd,
        null as appt_lmt_nte_90day_cd,
        null as appt_lmt_nte_90day_dte,
        gvt_appt_limit_hrs as appt_lmt_nte_hrs,
        gvt_appt_expir_dt as appt_nte_dte,
        null as appt_status_cd,
        gvt_type_of_appt as appt_type_cd,
        null as auo_pay_pct,
        null as auo_pay_prior_pct,
        null as authentication_dte,
        null as availability_pay_pct,
        null as awop_wgi_start_dte,
        {{ zero_to_null('he_awop_sep') }} as awop_ytd_hrs,
        barg_unit as bargaining_unit_cd,
        {{ calculate_base_hours('gvt_work_sched', 'std_hours') }} as base_hrs,
        birthdate as birth_dte,
        acct_cd as can_cd,
        null as can_new_cd,
        gvt_career_cond_dt as career_cond_appt_dte,
        gvt_career_cnv_due as career_tenure_conv_due_dte,
        citizenship_status as citizenship_cd,
        null as comp_area_cd,
        null as comp_area_prior_cd,
        null as comp_level_cd,
        null as comp_level_prior_cd,
        gvt_csrs_frozn_svc as csrs_frozen_svc_yrs_mths,
        null as current_appt_auth_cd_1,
        null as current_appt_auth_cd_2,
        location as duty_station_cd,
        null as duty_station_prior_cd,
        gvt_educ_level as educ_level_cd,
        effdt as effective_dte,
        emplid,
        empl_rcd,
        effseq,
        null as emp_review_rating_cd,
        null as emp_review_rating_pattern_cd,
        null as emp_review_rating_period_cd,
        null as emp_review_rating_prior_cd,
        null as emp_review_rating_scale_cd,
        null as emp_review_dte,
        null as emp_review_prior_dte,
        null as emp_review_prior_pattern_cd,
        null as emp_review_prior_period_cd,
        null as emp_review_prior_scale_cd,
        null as fegli_cd,
        gvt_fegli as fegli_code,
        gvt_fegli_living as fegli_living_benefit_cd,
        gvt_living_amt as fegli_living_benefit_amt,
        gvt_fers_coverage as fers_coverage_cd,
        first_name,
        flsa_status as flsa_cd,
        gvt_fin_disclosure as fnancl_disclosure_reqd_cd,
        gvt_fin_discl_date as fnancl_disclosure_dte,
        full_part_time as full_part_time_cd,
        null as func_class_cd,
        geo_code as geo_location_cd,
        grade as grade_cd,
        grade_entry_dt as grade_entry_dte,
        null as grade_prior_cd,
        gvt_handicap_cd as handicap_cd,
        hire_dt as hire_dte,
        hourly_rt as hourly_rate_amt,
        gvt_instr_pgm_cd as instr_pgm_cd,
        last_name,
        gvt_leg_auth_1 as leg_auth_cd_1,
        gvt_leg_auth_2 as leg_auth_cd_2,
        {{ build_legal_authority_text('gvt_par_auth_d1', 'gvt_par_auth_d1_2') }} as leg_auth_txt_1,
        {{ build_legal_authority_text('gvt_par_auth_d2', 'gvt_par_auth_d2_2') }} as leg_auth_txt_2,
        gvt_locality_adj as locality_adj_pct,
        null as locality_pay_area_cd,
        null as locality_pay_area_prior_cd,
        gvt_mand_ret_dt as mandatory_retire_dte,
        middle_name,
        military_status as military_svc_cd,
        gvt_cred_mil_svce as military_svc_cred_yrs_mths,
        gvt_military_comp as military_svc_comp_dte_cd,
        gvt_noa_code as noa_cd,
        gvt_noa_2nd_code as noa_cd_2,
        gvt_noa_suffix as noa_suffix_cd,
        gvt_noa_2nd_suffix as noa_suffix_cd_2,
        gvt_occ_series as occ_series_cd,
        null as occ_series_prior_cd,
        null as org_component_cd,
        null as org_component_prior_cd,
        null as org_structure_cd,
        null as org_structure_prior_cd,
        null as org_title_cd,
        null as org_title_prior_cd,
        gvt_pay_basis as pay_basis_cd,
        null as pay_basis_prior_cd,
        gvt_pay_plan as pay_plan_cd,
        null as pay_plan_prior_cd,
        null as pay_rate_determinant_cd,
        null as pay_rate_determinant_prior_cd,
        null as pay_status_cd,
        position_nbr as position_id,
        null as position_id_prior,
        gvt_posn_occ_cd as position_occupied_cd,
        gvt_posn_sens_cd as position_sensitivity_cd,
        postal as postal_cd,
        probation_dt as probation_dte,
        rehire_dt as rehire_dte,
        action_reason as remark_cd,
        gvt_rtnd_grade_beg as retained_grade_begin_dte,
        gvt_rtnd_grade_exp as retained_grade_expire_dte,
        gvt_scd_retire as scd_retire_dte,
        gvt_scd_leo as scd_leo_dte,
        gvt_scd_sevpay as scd_sev_pay_dte,
        gvt_scd_tsp as scd_tsp_dte,
        gvt_sec_clr_status as security_clearance_cd,
        gvt_clrnce_stat_dt as security_clearance_dte,
        gvt_ses_prob_dt as ses_probation_dte,
        sex as sex_cd,
        {{ zero_to_null('he_sl_balance') }} as sick_lv_cur_bal_hrs,
        {{ zero_to_null('he_sl_carryover') }} as sick_lv_prior_year_bal_hrs,
        {{ zero_to_null('he_sl_accrual') }} as sick_lv_ytd_accrd_hrs,
        {{ zero_to_null('he_sl_total') }} as sick_lv_ytd_used_hrs,
        ssn,
        state as state_cd,
        step as step_cd,
        step_entry_dt as step_entry_dte,
        null as step_prior_cd,
        gvt_supv_prob_dt as supv_probation_dte,
        gvt_supv_status as supv_status_cd,
        gvt_tenure as tenure_cd,
        termination_dt as termination_dte,
        gvt_total_salary as total_salary_amt,
        gvt_vet_pref as vet_pref_cd,
        gvt_vet_pref_appt as vet_pref_appt_cd,
        gvt_wgi_due_date as wgi_due_dte,
        gvt_wgi_status as wgi_status_cd,
        gvt_work_sched as work_schedule_cd,
        gvt_yr_of_degree as year_degree_attained,
        current_date() as load_date
    from enriched_data
)

select * from transformed
