{{
    config(
        materialized='incremental',
        schema='marts',
        unique_key=['event_id', 'remark_seq'],
        incremental_strategy='append'
    )
}}

{#
    This model replicates the action_remarks_all historical table from the Informatica pipeline.
    It appends daily records to maintain a complete history of all action remarks records.
    
    From ehrp2biis_afterload.sql:
    INSERT INTO action_remarks_all
    SELECT * FROM nknight.nwk_action_remarks_tbl
    WHERE event_id IN (SELECT event_id FROM nknight.nwk_action_primary_tbl WHERE load_date = TRUNC(sysdate));
    
    Note: The remarks are generated by stored procedures (HISTDBA.UPDT_ERP2BIIS_CRE8_REMARKS01_P)
    after the main ETL load. This model provides the structure for storing remarks data.
    
    In the dbt implementation, remarks would typically be populated through a separate
    process or post-hook that calls the equivalent Snowflake stored procedures.
#}

with action_events as (
    select distinct event_id, load_date
    from {{ ref('fct_action_primary') }}
),

remarks_source as (
    -- This CTE would join with the remarks source table if available
    -- For now, we create a placeholder structure that matches the target schema
    select
        ae.event_id,
        1 as remark_seq,
        null as remark_type_cd,
        null as remark_txt,
        ae.load_date
    from action_events ae
    where 1 = 0  -- No rows initially; remarks are generated by stored procedures
)

select *
from remarks_source

{% if is_incremental() %}
where load_date > (select coalesce(max(load_date), '1900-01-01') from {{ this }})
{% endif %}
